// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gives an option to use either `fileName` or `fileID` or `fileURL`
type FileRequestType int32

const (
	FileRequestType_FILE_NAME FileRequestType = 0
	FileRequestType_FILE_ID   FileRequestType = 1
	FileRequestType_FILE_URL  FileRequestType = 2
)

// Enum value maps for FileRequestType.
var (
	FileRequestType_name = map[int32]string{
		0: "FILE_NAME",
		1: "FILE_ID",
		2: "FILE_URL",
	}
	FileRequestType_value = map[string]int32{
		"FILE_NAME": 0,
		"FILE_ID":   1,
		"FILE_URL":  2,
	}
)

func (x FileRequestType) Enum() *FileRequestType {
	p := new(FileRequestType)
	*p = x
	return p
}

func (x FileRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (FileRequestType) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x FileRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileRequestType.Descriptor instead.
func (FileRequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

type MIME int32

const (
	MIME_MIME_UNSPECIFIED MIME = 0
	MIME_MIME_TXT         MIME = 1
	MIME_MIME_ZIP         MIME = 2
	MIME_MIME_PNG         MIME = 3
	MIME_MIME_JPG         MIME = 4
	MIME_MIME_JPEG        MIME = 5
	MIME_MIME_PDF         MIME = 6
	MIME_MIME_DOC         MIME = 7
	MIME_MIME_CSV         MIME = 8
	MIME_MIME_MD          MIME = 9
)

// Enum value maps for MIME.
var (
	MIME_name = map[int32]string{
		0: "MIME_UNSPECIFIED",
		1: "MIME_TXT",
		2: "MIME_ZIP",
		3: "MIME_PNG",
		4: "MIME_JPG",
		5: "MIME_JPEG",
		6: "MIME_PDF",
		7: "MIME_DOC",
		8: "MIME_CSV",
		9: "MIME_MD",
	}
	MIME_value = map[string]int32{
		"MIME_UNSPECIFIED": 0,
		"MIME_TXT":         1,
		"MIME_ZIP":         2,
		"MIME_PNG":         3,
		"MIME_JPG":         4,
		"MIME_JPEG":        5,
		"MIME_PDF":         6,
		"MIME_DOC":         7,
		"MIME_CSV":         8,
		"MIME_MD":          9,
	}
)

func (x MIME) Enum() *MIME {
	p := new(MIME)
	*p = x
	return p
}

func (x MIME) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MIME) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[1].Descriptor()
}

func (MIME) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[1]
}

func (x MIME) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MIME.Descriptor instead.
func (MIME) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

type Url_UrlHeader int32

const (
	Url_URL_UNSPECIFIED Url_UrlHeader = 0
	Url_HTTP            Url_UrlHeader = 1
	Url_HTTPS           Url_UrlHeader = 2
)

// Enum value maps for Url_UrlHeader.
var (
	Url_UrlHeader_name = map[int32]string{
		0: "URL_UNSPECIFIED",
		1: "HTTP",
		2: "HTTPS",
	}
	Url_UrlHeader_value = map[string]int32{
		"URL_UNSPECIFIED": 0,
		"HTTP":            1,
		"HTTPS":           2,
	}
)

func (x Url_UrlHeader) Enum() *Url_UrlHeader {
	p := new(Url_UrlHeader)
	*p = x
	return p
}

func (x Url_UrlHeader) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Url_UrlHeader) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[2].Descriptor()
}

func (Url_UrlHeader) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[2]
}

func (x Url_UrlHeader) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Url_UrlHeader.Descriptor instead.
func (Url_UrlHeader) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6, 0}
}

type FileContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Fetch list of files from the server/database and list them
	RequestType    FileRequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,proto3,enum=termvoid.FileRequestType" json:"request_type,omitempty"`
	FileIdentifier FileRequestType `protobuf:"varint,2,opt,name=file_identifier,json=fileIdentifier,proto3,enum=termvoid.FileRequestType" json:"file_identifier,omitempty"` // file_identifier => EITHER of `fileName`, `fileID`, or `URL`
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *FileRequest) GetRequestType() FileRequestType {
	if x != nil {
		return x.RequestType
	}
	return FileRequestType_FILE_NAME
}

func (x *FileRequest) GetFileIdentifier() FileRequestType {
	if x != nil {
		return x.FileIdentifier
	}
	return FileRequestType_FILE_NAME
}

type FileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files  []*FileMetadata `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Status string          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Status field for indicating upload status
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *FileResponse) GetFiles() []*FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FileHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileHistory) Reset() {
	*x = FileHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHistory) ProtoMessage() {}

func (x *FileHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHistory.ProtoReflect.Descriptor instead.
func (*FileHistory) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

type FileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name           string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size           int32           `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mime           MIME            `protobuf:"varint,4,opt,name=mime,proto3,enum=termvoid.MIME" json:"mime,omitempty"`
	Downloads      string          `protobuf:"bytes,5,opt,name=downloads,proto3" json:"downloads,omitempty"`
	ExpirationDate *ExpirationDate `protobuf:"bytes,6,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	ShareLink      *Url            `protobuf:"bytes,7,opt,name=share_link,json=shareLink,proto3" json:"share_link,omitempty"`
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *FileMetadata) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetMime() MIME {
	if x != nil {
		return x.Mime
	}
	return MIME_MIME_UNSPECIFIED
}

func (x *FileMetadata) GetDownloads() string {
	if x != nil {
		return x.Downloads
	}
	return ""
}

func (x *FileMetadata) GetExpirationDate() *ExpirationDate {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *FileMetadata) GetShareLink() *Url {
	if x != nil {
		return x.ShareLink
	}
	return nil
}

type ExpirationDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   int32 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month int32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year  int32 `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *ExpirationDate) Reset() {
	*x = ExpirationDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpirationDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpirationDate) ProtoMessage() {}

func (x *ExpirationDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpirationDate.ProtoReflect.Descriptor instead.
func (*ExpirationDate) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExpirationDate) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *ExpirationDate) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ExpirationDate) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlHeader Url_UrlHeader `protobuf:"varint,1,opt,name=url_header,json=urlHeader,proto3,enum=termvoid.Url_UrlHeader" json:"url_header,omitempty"`
	Url       string        `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *Url) GetUrlHeader() Url_UrlHeader {
	if x != nil {
		return x.UrlHeader
	}
	return Url_URL_UNSPECIFIED
}

func (x *Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_service_proto protoreflect.FileDescriptor

var file_proto_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x22,
	0x21, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76,
	0x6f, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x42, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x74, 0x65, 0x72, 0x6d,
	0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x22, 0x54, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x05, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x46, 0x69,
	0x6c, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0xf9, 0x01, 0x0a, 0x0c, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x4d, 0x49, 0x4d, 0x45,
	0x52, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x73, 0x12, 0x41, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x55, 0x72, 0x6c, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x4c, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x36, 0x0a, 0x0a, 0x75,
	0x72, 0x6c, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x55,
	0x72, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x09, 0x75, 0x72, 0x6c, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x35, 0x0a, 0x09, 0x55, 0x72, 0x6c, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x52, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x53, 0x10, 0x02, 0x2a, 0x3b, 0x0a, 0x0f,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0d, 0x0a, 0x09, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46,
	0x49, 0x4c, 0x45, 0x5f, 0x55, 0x52, 0x4c, 0x10, 0x02, 0x2a, 0x9a, 0x01, 0x0a, 0x04, 0x4d, 0x49,
	0x4d, 0x45, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x49, 0x4d, 0x45,
	0x5f, 0x54, 0x58, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x5a,
	0x49, 0x50, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x50, 0x4e, 0x47,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x4a, 0x50, 0x47, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x4a, 0x50, 0x45, 0x47, 0x10, 0x05, 0x12,
	0x0c, 0x0a, 0x08, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x50, 0x44, 0x46, 0x10, 0x06, 0x12, 0x0c, 0x0a,
	0x08, 0x4d, 0x49, 0x4d, 0x45, 0x5f, 0x44, 0x4f, 0x43, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4d,
	0x49, 0x4d, 0x45, 0x5f, 0x43, 0x53, 0x56, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4d,
	0x45, 0x5f, 0x4d, 0x44, 0x10, 0x09, 0x32, 0x88, 0x02, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x3c, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74,
	0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x15, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x65, 0x72, 0x6d,
	0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x3e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x15, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x65, 0x72,
	0x6d, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData = file_proto_service_proto_rawDesc
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_service_proto_rawDescData)
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_service_proto_goTypes = []interface{}{
	(FileRequestType)(0),   // 0: termvoid.FileRequestType
	(MIME)(0),              // 1: termvoid.MIME
	(Url_UrlHeader)(0),     // 2: termvoid.Url.UrlHeader
	(*FileContent)(nil),    // 3: termvoid.FileContent
	(*FileRequest)(nil),    // 4: termvoid.FileRequest
	(*FileResponse)(nil),   // 5: termvoid.FileResponse
	(*FileHistory)(nil),    // 6: termvoid.FileHistory
	(*FileMetadata)(nil),   // 7: termvoid.FileMetadata
	(*ExpirationDate)(nil), // 8: termvoid.ExpirationDate
	(*Url)(nil),            // 9: termvoid.Url
}
var file_proto_service_proto_depIdxs = []int32{
	0,  // 0: termvoid.FileRequest.request_type:type_name -> termvoid.FileRequestType
	0,  // 1: termvoid.FileRequest.file_identifier:type_name -> termvoid.FileRequestType
	7,  // 2: termvoid.FileResponse.files:type_name -> termvoid.FileMetadata
	1,  // 3: termvoid.FileMetadata.mime:type_name -> termvoid.MIME
	8,  // 4: termvoid.FileMetadata.expiration_date:type_name -> termvoid.ExpirationDate
	9,  // 5: termvoid.FileMetadata.share_link:type_name -> termvoid.Url
	2,  // 6: termvoid.Url.url_header:type_name -> termvoid.Url.UrlHeader
	3,  // 7: termvoid.FileService.UploadFile:input_type -> termvoid.FileContent
	4,  // 8: termvoid.FileService.DownloadFile:input_type -> termvoid.FileRequest
	4,  // 9: termvoid.FileService.GetFileInfo:input_type -> termvoid.FileRequest
	4,  // 10: termvoid.FileService.GetFileHistory:input_type -> termvoid.FileRequest
	5,  // 11: termvoid.FileService.UploadFile:output_type -> termvoid.FileResponse
	3,  // 12: termvoid.FileService.DownloadFile:output_type -> termvoid.FileContent
	7,  // 13: termvoid.FileService.GetFileInfo:output_type -> termvoid.FileMetadata
	6,  // 14: termvoid.FileService.GetFileHistory:output_type -> termvoid.FileHistory
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpirationDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_service_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_rawDesc = nil
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
