[package]
name = "void_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "void_lib"
path = "src/lib.rs"

[dependencies]
zip_archive = "1.2"

[dev-dependencies]
tempfile = "3.2"